### ISSUE TITLE
Please activate issues in https://github.com/ledahulevogyre/threeten-extra

### ISSUE THREAD

**Issue by catull** [ledahulevogyre/Le-gout-des-plantes#1]
Hello @ledahulevogyre 

I have tried to contact you.
Can you please activate Issues ?

Go to https://github.com/ledahulevogyre/threeten-extra/settings.
In the **Features** box, there is a checkbox next to **Issues**.
Check that box, please.

**Comment by ledahulevogyre** [comment]
Hi Carlo,

Here you go.
